# NOTE: This "production" version only contains differences from _config.yml.

baseurl: ""
environment: production
remote_data_prefix: "https://sustainabledevelopment-laos.github.io/data"

analytics:
  # For production, you likely want to enter a Google Analytics code below.
  ga_prod: ''
