# NOTE: This "production" version only contains differences from _config.yml.

# NOTE: For production "site configuration" in Open SDG, see the following file:
# _data/site_config_prod.yml
# This "site_config_prod.yml" file contains differences from "site_config.yml".

baseurl: "/sdg"
environment: production
